main:
  - name: Home
    url: /author/admin/
    weight: 10
  - name: Publications
    url: /publication/
    weight: 20
  - name: Teaching
    url: /courses/
    weight: 30
  - name: Genealogy
    url: /genealogy/
    weight: 40
  - name: Projects
    url: /project/
    weight: 50
  - name: Visualizations
    url: /visualizations/
    weight: 60
  - name: Contact
    url: /contact/
    weight: 70