main:
  - name: Home
    url: /author/admin/
    weight: 10
  - name: Publications
    url: /publication/
    weight: 20
  - name: Teaching
    url: /courses/
    weight: 30
  - name: Contact
    url: /contact/
    weight: 40
  - name: CV
    url: /author/admin/
    weight: 50