[build]
  command = "hugo --minify -b $DEPLOY_PRIME_URL"
  publish = "public"

[build.environment]
  # Versione di Hugo che usi in locale (quella che hai installato con brew)
  HUGO_VERSION = "0.128.2"

[[redirects]]
  from = "/"
  to = "/author/admin/"
  status = 301
  force = true
  
[[redirects]]
  from = "/%7B%7B"
  to = "/author/admin/"
  status = 301
  force = true